apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-opentelemetry-collector-agent-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: agent-collector
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      protocol: TCP
